---
kind: Namespace
apiVersion: v1
metadata:
  name: lb
  labels:
    name: lb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-backend
  namespace: lb
  labels:
    app: default-backend
spec:
  selector:
    matchLabels:
      app: default-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: default-backend
    spec:
      containers:
      - name: default-backend
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: index-file
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: index-file
        configMap:
          name: default-backend
---
apiVersion: v1
kind: Service
metadata:
  namespace: lb
  name: default-backend-svc
spec:
  selector:
    app: default-backend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-v1
  namespace: lb
  labels:
    app: hello-world-v1
spec:
  selector:
    matchLabels:
      app: hello-world-v1
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world-v1
    spec:
      containers:
      - name: hello-world-v1
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: index-file
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: index-file
        configMap:
          name: index-v1
---
apiVersion: v1
kind: Service
metadata:
  namespace: lb
  name: hello-world-v1-svc
spec:
  selector:
    app: hello-world-v1
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-v2
  namespace: lb
  labels:
    app: hello-world-v2
spec:
  selector:
    matchLabels:
      app: hello-world-v2
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world-v2
    spec:
      containers:
      - name: hello-world-v2
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: index-file
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: index-file
        configMap:
          name: index-v2
---
apiVersion: v1
kind: Service
metadata:
  namespace: lb
  name: hello-world-v2-svc
spec:
  selector:
    app: hello-world-v2
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-backend
  namespace: lb
data:
  index.html: |
    <html>
    <h1>i have no idea what iam doing </h1>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-v1
  namespace: lb
data:
  index.html: |
    <html>
    <h1>www.mh.org/v1 </h1>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-v2
  namespace: lb
data:
  index.html: |
    <html>
    <h1>www.mh.org/v2 </h1>
    </html>
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: lb
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: "nginx"
  defaultBackend:
    service:
      name: default-backend-svc
      port:
        number: 80
  rules:
    - host: www.mh.org
      http:
        paths:
        - path: /v1
          pathType: Prefix
          backend:
            service:
              name: hello-world-v1-svc
              port:
                number: 80
        - path: /v2
          pathType: Prefix
          backend:
            service:
              name: hello-world-v2-svc
              port:
                number: 80

