all:
  hosts:
    k8s-m1:
      ansible_host: 192.168.56.61
      ip: 192.168.56.61
      access_ip: 192.168.56.61
    k8s-m2:
      ansible_host: 192.168.56.62
      ip: 192.168.56.62
      access_ip: 192.168.56.62
    k8s-m3:
      ansible_host: 192.168.56.63
      ip: 192.168.56.63
      access_ip: 192.168.56.63
    k8s-n1:
      ansible_host: 192.168.56.51
      ip: 192.168.56.51
      access_ip: 192.168.56.51
    k8s-n2:
      ansible_host: 192.168.56.52
      ip: 192.168.56.52
      access_ip: 192.168.56.52
  children:
    kube_control_plane:
      hosts:
        k8s-m1:
        k8s-m2:
        k8s-m3:
    kube_node:
      hosts:
        k8s-n1:
        k8s-n2:
    etcd:
      hosts:
        k8s-m1:
        k8s-m2:
        k8s-m3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
