---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-for-nfs
spec:
  volumes:
    - name: nfs-data
      persistentVolumeClaim:
        claimName: nfs-claim
  containers:
    - name: test-container
      image: ubuntu
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: "/mnt/nfs"
          name: nfs-data
